apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-deployment-products
data:
  PORT: "3333"
  DATABASE_URL: "postgresql://postgres:yQRSkvruqzofhPAxgwGWwKziMUmMHEci@junction.proxy.rlwy.net:23706/railway?schema=products"

